dataset: BIRADS
task: classification

data:
  root_dir: data/
  pkl_file: datasets/USG_BIRDAS_Dataset.pkl
  color_channels: 4
  num_classes: 7
  bias_original_order: 0.6
  channel_order_classes: 24
  oversample: True
  normalize:
    mean: None
    std: None

train:
  batch_size: 16
  num_workers: 2
  pin_memory: true
  aug_trans:
    trans_seq: [random_horizontal_flip, multi_input, to_tensor]
    multi_input:
      size: 299
    flip_prob: 0.5
    fixed_resize:
      size: [299, 299]

eval:
  batch_size: 16
  num_workers: 2
  pin_memory: true
  ckpt_path: None
  aug_trans:
    trans_seq: [multi_input, to_tensor]
    multi_input:
      size: 299
    flip_prob: 0.5
    fixed_resize:
      size: [299, 299]

optim:
  num_epochs: 200
  optim_method: adam
  sgd:
    base_lr: 1e-2
    momentum: 0.9
    weight_decay: 5e-4
    nesterov: false
  adam:
    base_lr: 1e-3
    betas: [0.9, 0.999]
    weight_decay: 1e-4
    momentum: 0.9
    amsgrad: false
  use_lr_decay: false
  lr_decay_method: lambda
  cosine: None
  warmup_cosine: None

criterion:
  channel_order_loss_weight: 0.2
  criterion_method: ordered_loss
  ordered_loss:
    alpha: 1
    beta: 0.1

network:
  net: brnet
  model_name: mi_model
  model_suffix: BRNet
  drop_prob: 0.7
  use_parallel: false
  seed: 22
  num_gpus: 0
